/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'

// Create Virtual Routes

const MainIndexLazyImport = createFileRoute('/_main/')()
const MainCreatePresentationGenerateLazyImport = createFileRoute(
  '/_main/create-presentation-generate',
)()
const MainCreatePresentationLazyImport = createFileRoute(
  '/_main/create-presentation',
)()

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexLazyRoute = MainIndexLazyImport.update({
  path: '/',
  getParentRoute: () => MainRoute,
} as any).lazy(() => import('./routes/_main/index.lazy').then((d) => d.Route))

const MainCreatePresentationGenerateLazyRoute =
  MainCreatePresentationGenerateLazyImport.update({
    path: '/create-presentation-generate',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/create-presentation-generate.lazy').then(
      (d) => d.Route,
    ),
  )

const MainCreatePresentationLazyRoute = MainCreatePresentationLazyImport.update(
  {
    path: '/create-presentation',
    getParentRoute: () => MainRoute,
  } as any,
).lazy(() =>
  import('./routes/_main/create-presentation.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_main/create-presentation': {
      id: '/_main/create-presentation'
      path: '/create-presentation'
      fullPath: '/create-presentation'
      preLoaderRoute: typeof MainCreatePresentationLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/create-presentation-generate': {
      id: '/_main/create-presentation-generate'
      path: '/create-presentation-generate'
      fullPath: '/create-presentation-generate'
      preLoaderRoute: typeof MainCreatePresentationGenerateLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexLazyImport
      parentRoute: typeof MainImport
    }
  }
}

// Create and export the route tree

interface MainRouteChildren {
  MainCreatePresentationLazyRoute: typeof MainCreatePresentationLazyRoute
  MainCreatePresentationGenerateLazyRoute: typeof MainCreatePresentationGenerateLazyRoute
  MainIndexLazyRoute: typeof MainIndexLazyRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainCreatePresentationLazyRoute: MainCreatePresentationLazyRoute,
  MainCreatePresentationGenerateLazyRoute:
    MainCreatePresentationGenerateLazyRoute,
  MainIndexLazyRoute: MainIndexLazyRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof MainRouteWithChildren
  '/create-presentation': typeof MainCreatePresentationLazyRoute
  '/create-presentation-generate': typeof MainCreatePresentationGenerateLazyRoute
  '/': typeof MainIndexLazyRoute
}

export interface FileRoutesByTo {
  '/create-presentation': typeof MainCreatePresentationLazyRoute
  '/create-presentation-generate': typeof MainCreatePresentationGenerateLazyRoute
  '/': typeof MainIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_main': typeof MainRouteWithChildren
  '/_main/create-presentation': typeof MainCreatePresentationLazyRoute
  '/_main/create-presentation-generate': typeof MainCreatePresentationGenerateLazyRoute
  '/_main/': typeof MainIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/create-presentation' | '/create-presentation-generate' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/create-presentation' | '/create-presentation-generate' | '/'
  id:
    | '__root__'
    | '/_main'
    | '/_main/create-presentation'
    | '/_main/create-presentation-generate'
    | '/_main/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_main"
      ]
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/create-presentation",
        "/_main/create-presentation-generate",
        "/_main/"
      ]
    },
    "/_main/create-presentation": {
      "filePath": "_main/create-presentation.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/create-presentation-generate": {
      "filePath": "_main/create-presentation-generate.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/": {
      "filePath": "_main/index.lazy.tsx",
      "parent": "/_main"
    }
  }
}
ROUTE_MANIFEST_END */
